# Path to this file
SCRIPT_PATH="${(%):-%N}"
# Resolve symlink (macOS-compatible)
while [ -L "$SCRIPT_PATH" ]; do
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
done
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
export DOTFILES_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

export SHELL="zsh"
if [[ -f "$DOTFILES_DIR/shell/zsh/zshrc.local" ]]; then
  source "$DOTFILES_DIR/shell/zsh/zshrc.local"
fi

source "$DOTFILES_DIR/shell/common/aliases.sh"
source "$DOTFILES_DIR/shell/common/functions.sh"



# Tools
source "$DOTFILES_DIR/tools/homebrew/init.sh"
source "$DOTFILES_DIR/tools/starship/init.sh"
source "$DOTFILES_DIR/tools/pyenv/init.sh"
source "$DOTFILES_DIR/tools/nodejs/init.sh"





# # Initialize Zsh's completion system
# autoload -Uz compinit

# Lazy load syntax higlighting on first prompt
autoload -Uz add-zsh-hook


# Plugins

autoload -Uz compinit
compinit -C
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source "$DOTFILES_DIR/plugins/zsh-syntax-highlighting/init.sh"

# compinit -C # Skip compinit security checks (safe for single-user system)
# zstyle ':completions:*' rehash false
bindkey "^[[Z" end-of-line
