local zsh_dotfiles="$DOTFILES_DIR/zsh"

if [[ -f "$zsh_dotfiles/zshrc.local" ]]; then
    source "$zsh_dotfiles/zshrc.local"
fi

source "$zsh_dotfiles/common/functions.zsh"
source "$zsh_dotfiles/common/aliases.zsh"
source "$zsh_dotfiles/common/paths.zsh"



source "$zsh_dotfiles/conf.d/toolchains.zsh"
source "$zsh_dotfiles/conf.d/starship.zsh"
source "$zsh_dotfiles/conf.d/esp-idf.zsh"




export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

if type brew &>/dev/null; then
    FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - --no-rehash)"
export PATH="$PYENV_ROOT/shims:$PATH"

# Fix tkinter not installed with Pyenv installations
export TCL_TK_PATH="/usr/local/opt/tcl-tk"

pyenv-install-with-tk() {
    version="$1"
    if [ -z "$version" ]; then
        echo "Usage: pyenv-install-with-tk <python-version>"
        return 1
    fi

    env LDFLAGS="-L$(brew --prefix openssl@1.1)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix sqlite3)/lib -L$(brew --prefix xz)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix tcl-tk)/lib" \
    CPPFLAGS="-I$(brew --prefix openssl@1.1)/include -I$(brew --prefix readline)/include -I$(brew --prefix sqlite3)/include -I$(brew --prefix xz)/include -I$(brew --prefix zlib)/include -I$(brew --prefix tcl-tk)/include" \
    PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig:$(brew --prefix readline)/lib/pkgconfig:$(brew --prefix sqlite3)/lib/pkgconfig:$(brew --prefix xz)/lib/pkgconfig:$(brew --prefix zlib)/lib/pkgconfig:$(brew --prefix tcl-tk)/lib/pkgconfig" \
    pyenv install $version
}

# # Initialize Zsh's completion system
# autoload -Uz compinit

# Lazy load syntax higlighting on first prompt
autoload -Uz add-zsh-hook


# Plugins

autoload -Uz compinit
compinit -C
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source "$zsh_dotfiles/plugins/zsh-syntax-highlighting.zsh"

# compinit -C # Skip compinit security checks (safe for single-user system)
# zstyle ':completions:*' rehash false
bindkey "^[[Z" end-of-line
eval "$(starship init "$SHELL")"